vich_uploader:
    db_driver: orm

    mappings:
        archivos:
            uri_prefix: '/uploads/archivos_pdf'
            upload_destination: '%kernel.project_dir%/public/uploads/archivos_pdf'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
                #options: { property: 'slug'} # supposing that the object contains a "slug" attribute or a "getSlug" method
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
