controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
admin_generate_pdf:
    path: /admin/memo/{id}/pdf
    controller: App\Controller\Admin\MemoPdfController::class
